tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "exa"
brew "fzf"
brew "gh"
brew "n"
brew "peco"
brew "vim"
brew "mas"
cask "itsycal"
cask "raycast"
cask "google-chrome"
cask "docker"
mas "Slack", id: 803453959
