tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "python"
brew "git"
brew "exa"
brew "fzf"
brew "gh"
brew "n"
brew "peco"
brew "vim"
brew "mas"
brew "jq"
brew "fortune"
#brew "n"
brew "nvm"
cask "itsycal"
cask "raycast"
cask "google-chrome"
cask "docker"
cask "min"
mas "Slack", id: 803453959
mas "1Password", id: 1333542190
